suppressMessages(library(xlsx))
suppressMessages(library(tseries))
suppressMessages(library(forecast))
data <- read.xlsx("D:/Dropbox/16summer/Macroeconometrics/Problem Set3/mystery data.xls",sheetName="Sheet1",header=T)
data <- subset(data,complete.cases(data$ms1))
adf.test(data$ms1)
adf.test(data$ms2)
adf.test(data$ms3)
adf.test(data$ms4)
dms1 <- diff(data$ms1)
dms2 <- diff(data$ms2)
dms3 <- diff(data$ms3)
dms4 <- diff(data$ms4)
adf.test(dms1)
adf.test(dms2)
adf.test(dms3)
adf.test(dms4)
acf(dms1)
pacf(dms1)
acf(dms2)
pacf(dms2)
acf(dms3)
pacf(dms3)
acf(dms4)
pacf(dms4)
auto.arima(dms1)
Box.test(auto.arima(dms1)$resid,type="Ljung-Box")
auto.arima(dms2)
auto.arima(dms2,ic="aic",trace = TRUE,allowmean = FALSE)
arima(dms2,c(0,0,1),include.mean = FALSE)$aic
arima(dms2,c(1,0,0),include.mean = FALSE)$aic
arima(dms2,c(1,0,0),include.mean = FALSE)
Box.test(arima(dms2,c(1,0,0),include.mean = FALSE)$resid,type="Ljung-Box")
auto.arima(dms3)
Box.test(auto.arima(dms3)$resid,type="Ljung-Box")
auto.arima(dms4)
Box.test(auto.arima(dms4)$resid,type="Ljung-Box")
